# Generated by Django 2.0.4 on 2018-04-23 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
