# Generated by Django 2.0.4 on 2018-05-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=None, to='blog.Post')),
                ('user', models.ForeignKey(null=True, on_delete=None, to='blog.Profile', to_field='user')),
            ],
        ),
    ]
